### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by zoharbabin** [helmanofer/pydantic-prompter#35]
The | operator for type hinting is only supported in Python 3.10 and later. 
If you try to use Python 3.9 (default in aws lambda) you'll get this error: 
`TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`
in the following files:lines - 
base.py:19
base.py:25
bedrock_base.py:45
bedrock_base.py:58
bedrock_base.py:91
bedrock_anthropic.py:19
bedrock_anthropic.py:52
bedrock_cohere.py:31
cohere.py:21
bedrock_llama2.py:36
openai.py:46
llm_providers/__init__.py:26

The solution is to use Union and Optional wherever needed across the files:

```python
from typing import List, Union, Optional

def debug_prompt(self, messages: List[Message], scheme: Union[dict, str]):

def call(
        self,
        messages: List[Message],
        scheme: Optional[dict] = None,
        return_type: Optional[str] = None,
    ) -> str:

def _build_prompt(self, messages: List[Message], params: Union[dict, str]):

def get_llm(llm: str, model_name: str, parser: AnnotationParser, model_settings: Optional[Dict] = None) -> LLM:

```

**Comment by helmanofer** [comment]
[d72e279](https://github.com/helmanofer/pydantic-prompter/commit/d72e2799712f77afdafdf4cd3ed9d58a50bc02ab)
